### ISSUE TITLE
"Window motion makes things go crazy"

### ISSUE THREAD

**Issue by dccsillag** [dccsillag/picom#1]
As posted by @podiki in https://github.com/yshui/picom/issues/217#issuecomment-877732525:

> I did a quick modification of a PKGBUILD to install, no problems there. However, with animations enabled any window motion makes things go crazy (jump around, jitter, won't stop moving, flying around). My config (besides adding animations = true;) is here: https://github.com/podiki/dot.me/blob/master/picom/.config/picom.conf Perhaps the only notable thing is that this is on a 4k screen. (For comparison, same setup on jonaburg's fork worked well without any animation problems.)

**Comment by dccsillag** [comment]
I tried out your config (+ `animations = true;`), and a _may_ have seen a part of what you witnessed (but I don't think I saw it all, since all I saw wrongly was what seemed like offset shadows). Perhaps try temporarily disabling shadows? They are a bit tricky, and here, disabling them made the output as it is with my config.
4k doesn't appear to be the problem -- I just tested things out on my 4k monitor and it all works fine.

Could you perhaps record what is happening on your screen? Also, can you share the PKGBUILD you used? Who knows, might be something there.

**Comment by podiki** [comment]
Disabling shadows did the trick! Now everything looks good to me, animations are quick, no jumping around or other glitches (or at least for a first pass looks nice). Perhaps shadows need to be disabled on an animated window or something.

Nice work!

**Comment by podiki** [comment]
Oh, the PKGBUILD. I just changed the source git from one of the other picom fork AUR packages: https://gist.github.com/podiki/1a8b3466506e5c4d6a162138ea2accb9

**Comment by dccsillag** [comment]
Great!

I'll open a separate issue to deal with shadows, then, and close this one.
