### ISSUE TITLE
is there a way to tell wether the fork is installed

### ISSUE THREAD

**Issue by godalming123** [dccsillag/picom#25]
### Platform
Endeavour os linux bspwm

### GPU, drivers, and screen setup
Amd integrated graphics on laptop screen and 27 inch moniter with deafualt configuration so laptop screen is to the left of the monitors.
`glxinfo -B` gives me `bash: glxinfo: command not found`

### Environment
linux Endeavour os with bspwm

### picom version
vgit-31e58

<details>
<summary>Diagnostics</summary>
Rounded corner is only supported on legacy backends, it will be disabled
**Version:** vgit-ee7d9

### Extensions:

* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:

* Use Overlay: No
  (Another compositor is already running)
* Config file used: /home/whatever/.config/picom/picom.conf

### Drivers (inaccurate):

modesetting

### Backend: glx

* Driver vendors:
 * GLX: Mesa Project and SGI
 * GL: AMD
* GL renderer: AMD RAVEN (DRM 3.42.0, 5.15.10-arch1-1, LLVM 13.0.0)
* Accelerated: 1
</details>

### Configuration:
<details>
    <summary>Configuration file</summary>

```
#blur rule
blur: {
    method = "dual_kawase";
    strength = 3;
};
blur-exclude = [
	#"class_g = 'firefox'"
	#"class = 'jgmenu'"
]

#rounded corners
corner-radius = 8;
rounded-corners-exclude = [
    "class_g = 'polybar'",
    "window_type = 'dock'",
];
round-borders = 1;
detect-rounded-corners = true;

#fading
fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;

#shadow
#shadow = true;
shadow-radius = 10;
shadow-opacity = 1;
shadow-offset-x = -10;
shadow-offset-y = -10;
shadow-exclude = [
  "_NET_WM_WINDOW_TYPE:a = '_NET_WM_WINDOW_TYPE_NOTIFICATION'",
  "_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'",
  "_GTK_FRAME_EXTENTS@:c",
  "class_g = 'polybar'",
  "window_type = 'dock'",
];
shadow-ignore-shaped = false

#backend
backend = "glx";
glx-no-stencil = true;
glx-copy-from-font = false;
use-damage = true;
glx-no-rebind-pixmap = true;

```
</details>

### Expected behavior
Clear mention of the fact I'm using a fork of picom in the version or man pages

### Current Behavior
No clear mention stationg I am using the new version of picom

### Aditional info
As well as no clear sign of the picom version changing (other then no rounded cornres and the --version returning the commit that the forked repo is currently on except without a few charecters) there are no effects like swapping animations ...ETC

**Comment by dccsillag** [comment]
This is going to eventually be a PR into the main Picom repository. Therefore, it's not a good idea to add information stating "this is a fork." This is a temporary fork, and will [hopefully] eventually be merged.

If you want to check if you are using this fork of Picom via the manpage for debugging purposes, you can check if the animation-related flags are present.

> there are no effects like swapping animations ...ETC

That's because they aren't implemented here yet -- they are implemented in @pijulius' PR into this repository: https://github.com/dccsillag/picom/pull/22, but have not yet been merged.

**Comment by godalming123** [comment]
Is it possible that the reason it wasn't working is because I was cloning from the next branch instead of the implement window animations branch

**Comment by godalming123** [comment]
**UPDATE:** using https://github.com/dccsillag/picom/pull/22 and works brilliantly animating windows but I have a few issues see https://github.com/dccsillag/picom/pull/22#issuecomment-1007939560
