### ISSUE TITLE
cant uninstall

### ISSUE THREAD

**Issue by godalming123** [dccsillag/picom#26]
### Platform
endeaver os bspwm

### GPU, drivers, and screen setup
Amd integrated graphics on laptop screen and 27 inch moniter with deafualt configuration so laptop screen is to the left of the monitors.
`glxinfo -B` gives me `bash: glxinfo: command not found`

### Environment
linux Endeavour os with bspwm

### picom version
vgit-ee7d9
<details>
<summary>Diagnostics</summary>
[ 24/12/21 09:00:24.754 get_cfg WARN ] Rounded corner is only supported on legacy backends, it will be disabled
**Version:** vgit-ee7d9

### Extensions:

* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:

* Use Overlay: No
  (Another compositor is already running)
* Config file used: /home/whatever/.config/picom/picom.conf

### Drivers (inaccurate):

modesetting

### Backend: glx

* Driver vendors:
 * GLX: Mesa Project and SGI
 * GL: AMD
* GL renderer: AMD RAVEN (DRM 3.42.0, 5.15.11-arch2-1, LLVM 13.0.0)
* Accelerated: 1
</details>

### Configuration:
<details>
    <summary>Configuration file</summary>

```
#window swapping
animation = true;

#blur rule
blur: {
    method = "dual_kawase";
    strength = 3;
};
blur-exclude = [
	#"class_g = 'firefox'"
	#"class = 'jgmenu'"
]

#rounded corners
corner-radius = 8;
rounded-corners-exclude = [
    "class_g = 'polybar'",
    "window_type = 'dock'",
];
round-borders = 8;
detect-rounded-corners = true;

#fading
fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;

#shadow
#shadow = true;
shadow-radius = 10;
shadow-opacity = 1;
shadow-offset-x = -10;
shadow-offset-y = -10;
shadow-exclude = [
  "_NET_WM_WINDOW_TYPE:a = '_NET_WM_WINDOW_TYPE_NOTIFICATION'",
  "_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'",
  "_GTK_FRAME_EXTENTS@:c",
  "class_g = 'polybar'",
  "window_type = 'dock'",
];
shadow-ignore-shaped = false

#backend
backend = "glx";
glx-no-stencil = true;
glx-copy-from-font = false;
use-damage = true;
glx-no-rebind-pixmap = true;

```
</details>

### Expected behavior
Docs on how to uninstall after building

### Current Behavior
No documentation on uninstalling.

**Comment by dccsillag** [comment]
Again, this is not an issue with us, but upstream Picom.

In any case, if I'm not mistaken, Meson (the build system used by Picom) has a way to uninstall binaries(&manpages?): `ninja -C build uninstall`. You could also just install another version of Picom over it, if that's what you ultimately want to do.

**Comment by godalming123** [comment]
Thanks this worked for me and I have made a PR on the main picom
