### ISSUE TITLE
Buggy borders with rounded corners

### ISSUE THREAD

**Issue by godalming123** [dccsillag/picom#28]
### Platform
Arch bspwm

### GPU, drivers, and screen setup
Amd drivers single monietr

### Environment
bspwm

### picom version
Your add window animations fork

### Steps of reproduction
1. use the glx backend
2. use borders
3. use rounded borders

### Expected behavior
The borders are not scaled with the window

### Current Behavior
Th borders are scaled with the window see https://youtu.be/0f3Cj5i-s0M (apologies for the bad quility)

**Comment by dccsillag** [comment]
Yeah, I noticed that -- I stil haven't tackled it.

There are two issues with rounded borders actually:

1. When a new window is opened, it doesn't have rounded corners until it's animated
2. The one you mentioned -- the old pixmap keeps its rounded corners from when the window had different dimensions.

I'm confident the first one will be solved. As for the second one, I still don't know the specifics, but hopefully we'll be able to solve them as well.

**Comment by dccsillag** [comment]
Solved in 1972d9585f3cb3336441e7f4a9cb5c6d5f684cc9!

To be precise, just the second item from my message above. The first one is to be tracked at https://github.com/dccsillag/picom/issues/30.
