### ISSUE TITLE
Window content interpolation for size animation

### ISSUE THREAD

**Issue by dccsillag** [dccsillag/picom#3]
When we are animating a from a smaller window to a larger one, we are fine; we can just truncate the window contents during the animation.

However, when we are animating from a larger window to a smaller one, during the animation the window already is smaller, and so we end up with the size-animating region being filled with something that depends on the backend (if I'm not mistaken, it's a solid white on legacy backends, and a transparent color on new experimental backends).

What we should do instead, as proposed in https://github.com/yshui/picom/issues/217#issuecomment-586858726, is interpolate the window contents based on a saved version of the old contents and the current pixmap.

**Comment by dccsillag** [comment]
Note to self: I think we can avoid having to touch the actual rendering code (which I believe is backend-specific) and having to create a special window mode if we instead do the following:

The old and the new window contents are represented as two pixman frames, one on top of the other, with `eta*window_alpha, (1-eta)*window_alpha` transparency (where `eta` is some sort of progress indicator, ranging from 0 (start of animation) to 1 (end of animation)).

That is, we use the already existing color blending calculations to do the interpolation for us. As long as the two frames are side-by-side in the z-order, I think we should get the same thing as we would if we were to do the blending by hand, but in a more elegant and more concise manner.

**Comment by phisch** [comment]
If you need a hint for the pixmap morphing: it's best to morph both the "before" and "after" transition pixmaps in size (both get distorted during the transition to fit the current state). Keep the before at 100% opacity, and do a linear transition of the after pixmaps opacity from 0 to 1. This is basically how every modern wm does this.

**Comment by dccsillag** [comment]
Thank's for the tip! It's very comforting to know that that's essentially how modern WMs/DEs do it.
I think that's what I meant with the `eta*window_alpha` (for the "after" window) and the `(1-eta)*window_alpha` (for the "before" window). But I'm still trying to figure out what `eta` could be with spring animations. I'm thinking of something like `eta = 1 - d(p_n,q)/d(p_0,q)` (where `p_0` is the starting point, `p_n` is the current animation point, `q` is the destination point, and `d` is the euclidean metric). I guess if we do it this way, we also end up getting the spring animation's natural-ness into the pixmap animation, which is neat.

What I still don't know (but haven't really started to think about yet) is how I would go about adding a new pixmap for the same window in Picom. I'll take a look.

**Comment by dccsillag** [comment]
Ooops, I just understood what you actually meant. I guess I'll give both ways a go, see which works better.

EDIT: actually, what you proposed makes a lot more sense, because alpha blending with an opache background already does a convex combination. I'm going to roll with that.

**Comment by dccsillag** [comment]
It turns out this kind of had to be backend-specific. But the diff isn't too large, so that's something.

My focus is on the experimental backends, largely due to the following excerpt from picom's README:

> New backend features will only be implemented on the new backends from now on, and the old backends will eventually be phased out after the new backends stabilize.

So far, it's working on the GL* backends (anything that uses `gl_common.[ch]`).
I'll take a look at the `xrender` backend (the only one remaining) soon-ish.

There are two "details" which still need to be sorted on the GL* backend implementation, though:
- "Resize" interpolation: Picom already specified GL_NEAREST, which makes sense, since it should be a tad faster. But since we actually do scaling for animations, we might want to take a look at GL_LINEAR instead, particularly its performance implications. Maybe we should use GL_LINEAR iff animations are enabled?
- Alphas to use: my first attempt was to use what was suggested by @phisch above, which worked great for opaque windows; however, when trying it on non-opaque windows, they ended up having sudden jumps in transparency. When using what I had thought of earlier, this issue gets fixed, but then, for some weird reason (which needs to be understood), opaque windows become transparent in the middle of the animation. What is currently done in the code is to check whether the window is opaque; if it is, use the former approach, otherwise, use the latter. This seems to work OK, but is not ideal.

**Comment by dccsillag** [comment]
Update: the interpolation (nearest vs. linear/bilinear) curiously doesn't appear to cause a big difference, so I think I'm keeping it at nearest.

Alphas to use: this still remains to be seen, but should probably become its own issue (EDIT: https://github.com/dccsillag/picom/issues/17).

Also, xrender backend is now nearly done, with commit 87b34526fd7d7eac1096714fc2038455c09a0db7. The only thing not done is a weird issue regarding damaging of specific windows (this will also become its own issue; EDIT: https://github.com/dccsillag/picom/issues/18).

**Comment by dccsillag** [comment]
Now that these issues have been created, I'm closing this one.
