### ISSUE TITLE
rounded corners / border colors not working correctly on firefox, electron and counting

### ISSUE THREAD

**Issue by beyond9thousand** [dccsillag/picom#36]
my active border color is blue, as you see on the terminal to the right in my second workspace.

https://user-images.githubusercontent.com/77363063/175829415-42c706b3-c0c1-4a62-89a1-d0e2a0c33c03.mp4

window manager: bspwm
version: vgit-51b21

**Comment by beyond9thousand** [comment]
exiting full screen mode turns the corners sharp at random events

https://user-images.githubusercontent.com/77363063/175830433-7a39ca67-f815-4e31-9819-7e8d49fdcc9e.mp4

**Comment by beyond9thousand** [comment]
i3lock starts glitching when system wakes up from sleep, and after loggin back in, all corners for all kinds of windows are broken (not rounded + bad artefacting)

**Comment by kitt-cat** [comment]
I'm wondering if this fork contains the work done by ibhagwan and sdhand to improve rounded corners? Afaik the latest rounded corner branch is this one: https://github.com/ibhagwan/picom/tree/next-rebase; the readme notes that not all their code was upstreamed. Perhaps if you're like me and were using that fork previously, the glitches are due to missing some of their improvements?

**Comment by dccsillag** [comment]
> I'm wondering if this fork contains the work done by ibhagwan and sdhand to improve rounded corners? Afaik the latest rounded corner branch is this one: https://github.com/ibhagwan/picom/tree/next-rebase; the readme notes that not all their code was upstreamed. Perhaps if you're like me and were using that fork previously, the glitches are due to missing some of their improvements?

While it's possible that the issues originate (at least in part) due to this, these improvements are outside of the scope of [the PR which this fork correspond to](https://github.com/yshui/picom/pull/772). Therefore, if they are to be upstreamed, it will be in the form of follow-up work.

**Comment by dccsillag** [comment]
So, I'm finally looking at this properly. While I see the problem in the second video (about coming out of fullscreen mode), I'm afraid I wasn't able to spot the problem in the first one (my best guess is that maybe the shape of the rounded borders?). Could you please elaborate?

Also, regarding the full screen issue in particular, it shouldn't have anything to do with ibhagwan's work, so it will definitely be fixed still in this PR.

**Comment by beyond9thousand** [comment]
Sorry for the late response, I have fiddled with the config quite a bit since I last opened the issue. Turns out, setting `force-win-blend` to true does the trick to display the right colors (no idea why).

The problem of windows randomly losing rounded corners after returning from full screen state still remains.

**Comment by DreamMaoMao** [comment]
> Sorry for the late response, I have fiddled with the config quite a bit since I last opened the issue. Turns out, setting `force-win-blend` to true does the trick to display the right colors (no idea why).
> 
> The problem of windows randomly losing rounded corners after returning from full screen state still remains.

Did you fix this problem about that ` losing rounded corners after returning from full screen state `,i have the same problem
