### ISSUE TITLE
Animations don't work

### ISSUE THREAD

**Issue by D3SK3R** [dccsillag/picom#37]
### Platform
Manjaro 5.15.49-xanmod1-tt-1

### GPU, drivers, and screen setup
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel (0x8086)
    Device: Mesa Intel(R) HD Graphics 5500 (BDW GT2) (0x1616)
    Version: 22.1.2
    Accelerated: yes
    Video memory: 1359MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) HD Graphics 5500 (BDW GT2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 22.1.2
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6 (Compatibility Profile) Mesa 22.1.2
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 22.1.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

### Environment
bspwm

### picom version
**Version:** vgit-cd505

### Extensions:

* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:

* Use Overlay: Yes
* Config file used: /home/d3sk3r/.config/picom/picom.conf

### Drivers (inaccurate):

Intel

### Backend: glx

* Driver vendors:
 * GLX: Mesa Project and SGI
 * GL: Intel
* GL renderer: Mesa Intel(R) HD Graphics 5500 (BDW GT2)
* Accelerated: 1

### Configuration:
animations = true
animation-stiffness = 300.0
animation-dampening = 20.0
animation-window-mass = 1
animation-clamping = true
animation-for-open-window = "zoom";
animation-for-menu-window = "slide-down";
animation-for-transient-window = "slide-down";

### Steps of reproduction

1. git clone the repo
2. install picom (meson --buildtype=release . build;ninja -C build;sudo ninja -C build install)
3. run with --experimental-backends

### Expected behavior
Animations when opening/closing changing windows position and etc

### Current Behavior
0 animations

### Other details
Before trying this fork I tried pijulius' one, and the animations work great, but it's old and because of that, it has some bugs and the rounded corners doesn't work with --experimental-backends, that's when I came across this fork, everything works fine, but the animations simply don't, for some reason there's no #animations# section inside the [picom.sample.conf](https://github.com/dccsillag/picom/blob/next/picom.sample.conf) but taking a look at #34 it's probably the same syntax of pijulius's fork (the part I wrote in the configuration section)

**Comment by raven2cz** [comment]
Did you switch to branch _implement-window-animations_? Default branch next is original branch. I don't see commit with animations in next branch. Whole work I see in implement-window-animations branch.

**Comment by ShadiestGoat** [comment]
I'm in bspwm as well, and it doesn't seem to work for me

**Comment by dskxkzn** [comment]
> Did you switch to branch _implement-window-animations_? Default branch next is original branch. I don't see commit with animations in next branch. Whole work I see in implement-window-animations branch.

Yes, even after switching branches, no animations

**Comment by dskxkzn** [comment]
Well, no it worked, it was actually my inexperience with git apparently, for some reason just switching the branch after cloning the repo didn't actually change anything, so I downloaded as zip from here and it worked.
