### ISSUE TITLE
Rounded Corners with Dual_Kawase blur, artifacts in corner

### ISSUE THREAD

**Issue by overtoneblue** [dccsillag/picom#43]
Hi, I just wanted to note that there are some small issues with rounded corners using dual_kawase blur method, currently on arch, i3, and using latest window animations branch and nvidia 3070ti with latest drivers. I tested multiple different picom forks and standard picom, I noticed that yshui's picom also has this issue when using dual_kawase blur and opacity. However picom-ibhagwan-git from the AUR did not have this issue, I have built from the latest changes on this branch, as well as used the AUR package picom-animations-git and both had the issue. 
![image](https://user-images.githubusercontent.com/93581805/187658857-4987d4d4-01ae-4d79-97ef-83057642359c.png)

**Comment by dccsillag** [comment]
Hi,
If upstream (i.e., standard, i.e., yshui's) picom also has this issue, then this is outside of the scope of this repository -- after all, the purpose of the work here is to be merged to upstream in [this PR](https://github.com/yshui/picom/pull/772). Such improvements should be done in a separate PR.

Nevertheless, thank you for your work, looking for where these issues occur! This should be handy for when/where this issue *does* get tackled.

**Comment by overtoneblue** [comment]
Sounds good, thanks for all your work on this fork !
