### ISSUE TITLE
Spectacle crashes picom

### ISSUE THREAD

**Issue by DesjardinsRepos** [dccsillag/picom#48]
Basically the title, whenever spectacle starts its overlay picom crashes

[info log (video)](https://youtu.be/JKRBv6jN7bM)
[debug log (video)](https://www.youtube.com/watch?v=1kEpuSkeBv8)

Specs:
Arch x64
i3-gaps
rx 5700, xf86-video-amdgpu 22.0.0-1, mesa 22.1.7-1
picom-animations-git 1770_Next.208.g51b2135_2022.05.29-1
[config](https://github.com/DesjardinsRepos/home-files-public/blob/master/dotfiles/picom/conf) 
[glxinfo -B](https://pastebin.com/00N0XaXy)
[picom --diagnostics](https://pastebin.com/UYBy5PcW)

**Comment by dccsillag** [comment]
Whoa, that's very weird.

Does this happen in upstream (current) Picom? Also, since we still haven't merged recent upstream commits, does this also happen in the latest upstream commit we have (cd50596, I think)?

**Comment by DesjardinsRepos** [comment]
Ive been trying to reproduce this issue for a few days now, turns out my script was calling picom with `--experimental-backends` enabled, which fixes these crashes.

[Same behaviour on cd50596](https://youtu.be/Lo_ur4nCIGE)

I dont know if youre still working on the legacy backends, if not you can close this issue

**Comment by dccsillag** [comment]
Ah, nice catch! Yeah, we're not going to implement stuff on the legacy backends (especially considering that they aren't even the default anymore on upstream), so I'll be closing this.

Thanks for the notice!
