### ISSUE TITLE
aur package not found

### ISSUE THREAD

**Issue by Synchlaire** [dccsillag/picom#56]
is there a reason why this got removed from the aur? it used to be my favorite fork :(

**Comment by dccsillag** [comment]
I have no idea, I've never managed any package for this. Though, if I were to guess, it's something to do with the recent momentum in the new animations PR.

**Comment by Synchlaire** [comment]
aaah, i see. thanks for the quick reply!

guess i'll eventually have to start looking for another compositor if that's the case. meanwhile i'll just keep using this one
